### ISSUE TITLE
cli/serve stopped working after update from 1.5.2 to 1.6.0

### ISSUE THREAD

**Issue by sexta13** [webpack/webpack-cli#2993]
**Describe the bug**

After last update of cli/serve to 1.6.0, I get this error when running `yarn start` command:

```
[webpack-cli] Unable to load '@webpack-cli/serve' command
[start:app] [webpack-cli] TypeError: options.forEach is not a function
```

If I revert in yarn.lock to version 1.5.2 I don't get this error.

**To Reproduce**

This is what I have in package.json:
```
	"webpack": "5.48.0",
    "webpack-bundle-analyzer": "4.4.2",
    "webpack-cli": "4.7.2",
    "webpack-dev-server": "3.11.2"
```
yarn.lock for cli/serve looks like this:
```
"@webpack-cli/serve@^1.5.1":
  version "1.6.0"
  resolved "https://nexus.wfm.talkdeskstg.com/repository/tdx-npm/@webpack-cli/serve/-/serve-1.6.0.tgz#2c275aa05c895eccebbfc34cfb223c6e8bd591a2"
  integrity sha512-ZkVeqEmRpBV2GHvjjUZqEai2PpUbuq8Bqd//vEYsp63J8WyexI8ppCqVS3Zs0QADf6aWuPdU+0XsPI647PVlQA==
```

**Expected behavior**

The expected behavior is that the webpack serve runs without giving the above error, as it is working with 1.5.2, since in changelog it doesn't show any breaking changes

**Screenshots**

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-cli/issues/2990

**Comment by sexta13** [comment]
ups, sorry. I did a search but somehow that one missed me. Thanks
